spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
management:
  endpoint:
    health:
      show-details: never
logging:
  structured:
    format:
      console: ecs
